steps:
# Build the container image
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/trigger:${SHORT_SHA}', '.']
  id: Building the Artifact image

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/trigger:${SHORT_SHA}']
  id: Pushing the image to Artifact Registry

# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_SERVICE_NAME}', '--image', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/trigger:${SHORT_SHA}', '--region', 'asia-southeast2', '--platform', 'managed', "--allow-unauthenticated"]

images:
- 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}/trigger'

options:
  logging: CLOUD_LOGGING_ONLY